# Minimal JupyterBook Configuration for Education Playground

title: Education Playground
author: Mykolas Perevicius
copyright: "2025"

execute:
  execute_notebooks: off

repository:
  url: https://github.com/mykolas-perevicius/Education_Playground
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  baseurl: "https://mykolas-perevicius.github.io/Education_Playground/"
  extra_footer: |
    <script src="_static/js/onboarding.js"></script>
  extra_css:
    - _static/css/custom.css

sphinx:
  config:
    html_theme_options:
      navigation_depth: 4
      show_toc_level: 2
      navbar_align: "left"
      # Layout fixes for proper content width
      home_page_in_toc: false
      collapse_navigation: false
      navigation_with_keys: true
      # Content width settings
      article_header_start: []
      article_header_end: []
      primary_sidebar_end: []

launch_buttons:
  colab_url: "https://colab.research.google.com"

parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - tasklist
